### ISSUE TITLE
file format

### ISSUE THREAD

**Issue by hexxter** [Velleman/Vertex#1]
Why not the 3d Printer friendly .stl ?
I could not open the .dwg files DRAFTSIGHT says the files are damaged.

**Comment by BrenuDev** [comment]
Stl would be useless because you can't modify it.
You have 3 file types you can choose from. 
Are some files working and some not?

**Comment by BrenuDev** [comment]
Just downloaded draftsight and everything seems fine

**Comment by hexxter** [comment]
Hi,

i can load stl in blender and modify it. But it is more important too
print it with an 3D Printer and for this STL is the one and  only format.

Am 02.03.2015 um 16:31 schrieb Brecht Nuyttens:

**Comment by hexxter** [comment]
Hi,

sorry not on my PC ;) I have test it with multiple different parts from
your repository.

BR ALexander

Am 02.03.2015 um 16:37 schrieb Brecht Nuyttens:

**Comment by BrenuDev** [comment]
And using a CAD converter like this one?
http://www.anycad.net/the-free-3d-model-converter-anycad-exchange3d.html

**Comment by hexxter** [comment]
Hi,

sorry i'm a linux user Ubuntu 14.04. But i test the online version of
anycad.

BR Alexander

Am 03.03.2015 um 14:07 schrieb Brecht Nuyttens:
